import type { VerificationResult } from "@/types/domain";

export function runFraudHeuristics(text: string, metadata?: Record<string, unknown>): string[] {
  const flags: string[] = [];
  const normalized = text.toLowerCase();

  if (/(template|sample|dummy certificate)/i.test(normalized)) flags.push("template_pattern_detected");
  if ((metadata?.edited as boolean) === true) flags.push("metadata_indicates_edit");
  if ((metadata?.createdAt as string)?.includes("1970")) flags.push("suspicious_timestamp");
  if (normalized.includes("generated by ai")) flags.push("possible_ai_generated_proof");

  return flags;
}

export function combineVerification(ai: VerificationResult, localFlags: string[]): VerificationResult {
  return {
    ...ai,
    suspiciousFlags: Array.from(new Set([...ai.suspiciousFlags, ...localFlags]))
  };
}
